name: Node.js CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  NODE_ENV: test
defaults:
  run:
    working-directory: src
jobs:
  ci-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm i
      - name: Running tests
        run: npm test

jobs:
  cd-api:
      name: Deploy
      runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh deploy.sh